#!/usr/bin/env python3
"""
PAM SSH 2FA - Approval Server
=============================

A lightweight HTTP server that handles link-based authentication approvals.
Users click an approval link in their push notification instead of typing a code.

OVERVIEW
--------
When a user authenticates via SSH with auth_method=link or auth_method=both:
1. PAM module creates an approval request file with a unique token
2. PAM sends notification containing approval link
3. User opens the link and explicitly confirms on their phone
4. This server marks the approval as granted after the confirmation POST
5. PAM module detects approval and grants SSH access

INSTALLATION
------------
This server runs as a systemd service. Install with:
    sudo ./install.sh

Or manually:
    sudo cp approval_server.py /etc/pam-ssh-2fa/
    sudo cp pam-ssh-2fa-server.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable pam-ssh-2fa-server
    sudo systemctl start pam-ssh-2fa-server

CONFIGURATION
-------------
Server settings are in /etc/pam-ssh-2fa/config.ini under [server]:
    port = 9110
    url = https://your-server.example.com:9110
    # Optional native TLS -- set both or neither:
    # tls_cert = /etc/pam-ssh-2fa/tls/fullchain.pem
    # tls_key = /etc/pam-ssh-2fa/tls/privkey.pem

The 'url' is what appears in notification links. It must be reachable
from the user's phone (public IP, hostname, or Tailscale address).
pam_ssh_2fa.py refuses to build a link with an insecure http:// url for
a public host (see SECURITY CONSIDERATIONS below), so this server must
actually be reachable over HTTPS whenever it isn't confined to a
private network.

SECURITY CONSIDERATIONS
-----------------------
- Tokens are cryptographically random and single-use
- Approvals expire after the configured timeout (default 5 minutes)
- Server binds to 0.0.0.0 by default (all interfaces)
- Consider firewall rules to limit access if needed
- Approval links are bearer credentials: whoever observes one in
  transit can approve the associated SSH login. For any deployment
  reachable outside a private/loopback network, use HTTPS -- either
  set tls_cert/tls_key above to serve it natively, or run this server
  on loopback/an internal address behind a TLS-terminating reverse
  proxy (nginx, Caddy, etc). Plain HTTP to a public host is rejected
  by pam_ssh_2fa.py by default (see [server] allow_insecure_http in
  config.ini to override, not recommended).
- If deploying over Tailscale with a *.ts.net hostname (rather than a
  raw tailnet IP), `tailscale cert` issues a free publicly-trusted
  certificate for that hostname -- pair it with tls_cert/tls_key above.

ENDPOINTS
---------
GET /approve/<token>  - Display an authentication request
POST /approve/<token> - Approve after explicit confirmation
GET /health           - Health check endpoint

AUTHOR
------
Generated by Claude (Anthropic) for SSH 2FA push notification authentication.

LICENSE
-------
MIT License - Use and modify freely.
"""

# =============================================================================
# IMPORTS
# =============================================================================

import os
import sys
import json
import time
import logging
import argparse
import configparser
import html
import re
import secrets
import tempfile
import ssl
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional, Tuple

# Use built-in http.server for minimal dependencies
# No Flask required - keeps it simple and dependency-free
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import threading

# =============================================================================
# CONFIGURATION
# =============================================================================

# Default paths
DEFAULT_CONFIG_FILE = "/etc/pam-ssh-2fa/config.ini"
DEFAULT_APPROVALS_DIR = "/var/run/pam-ssh-2fa/approvals"
DEFAULT_PORT = 9110
DEFAULT_BIND_ADDRESS = "0.0.0.0"

# HTML templates (minimal, accessible)
HTML_SUCCESS = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SSH Access Approved</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            text-align: center;
        }}
        .success {{
            color: #22863a;
            font-size: 24px;
            margin-bottom: 20px;
        }}
        .details {{
            color: #666;
            margin-top: 20px;
        }}
    </style>
</head>
<body>
    <div class="success">[OK] Access Approved</div>
    <p>SSH authentication for <strong>{user}</strong> has been approved.</p>
    <p>You can close this page and return to your terminal.</p>
    <div class="details">
        <p>Host: {host}</p>
        <p>From: {rhost}</p>
        <p>Time: {time}</p>
    </div>
</body>
</html>
"""

HTML_CONFIRM = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm SSH Access</title>
    <style>
        body {{ font-family: sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; }}
        button {{ font-size: 1.1rem; padding: 0.7rem 1.2rem; }}
    </style>
</head>
<body>
    <h1>Confirm SSH Access</h1>
    <p>Approve this SSH authentication request only if you initiated it.</p>
    <dl>
        <dt>User</dt><dd>{user}</dd>
        <dt>Host</dt><dd>{host}</dd>
        <dt>From</dt><dd>{rhost}</dd>
    </dl>
    <form method="post" action="/approve/{token}">
        <input type="hidden" name="confirmation_token" value="{confirmation_token}">
        <button type="submit">Approve SSH login</button>
    </form>
</body>
</html>
"""

HTML_ERROR = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SSH Approval Error</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            text-align: center;
        }}
        .error {{
            color: #cb2431;
            font-size: 24px;
            margin-bottom: 20px;
        }}
    </style>
</head>
<body>
    <div class="error">[ERROR] {title}</div>
    <p>{message}</p>
</body>
</html>
"""

# =============================================================================
# LOGGING SETUP
# =============================================================================


def setup_logging(debug: bool = False, log_file: Optional[str] = None):
    """
    Configure logging for the approval server.

    Args:
        debug: Enable debug level logging
        log_file: Optional path to log file (also logs to stdout)
    """
    level = logging.DEBUG if debug else logging.INFO
    format_str = "%(asctime)s [%(levelname)s] %(message)s"

    handlers = [logging.StreamHandler(sys.stdout)]

    if log_file:
        try:
            log_dir = os.path.dirname(log_file)
            if log_dir and not os.path.exists(log_dir):
                os.makedirs(log_dir, mode=0o750)
            handlers.append(logging.FileHandler(log_file))
        except OSError as e:
            print(f"Warning: Could not create log file: {e}")

    logging.basicConfig(level=level, format=format_str, handlers=handlers)


# =============================================================================
# CONFIGURATION LOADER
# =============================================================================


class ServerConfig:
    """
    Configuration manager for the approval server.

    Loads settings from the main PAM 2FA config file.

    Attributes:
        port (int): Port to listen on
        bind_address (str): Address to bind to (default 0.0.0.0)
        approvals_dir (str): Directory for approval request files
        debug (bool): Enable debug logging
        log_file (str): Path to log file
        tls_cert (str): Path to a PEM certificate (chain) file, or ""
            to serve plain HTTP -- see the ApprovalServer/main()
            docstrings for when that's appropriate
        tls_key (str): Path to the PEM private key matching tls_cert
    """

    def __init__(self, config_file: str = DEFAULT_CONFIG_FILE):
        """
        Initialize server configuration.

        Args:
            config_file: Path to the main config.ini file
        """
        self.port = DEFAULT_PORT
        self.bind_address = DEFAULT_BIND_ADDRESS
        self.approvals_dir = DEFAULT_APPROVALS_DIR
        self.debug = False
        self.log_file = "/var/log/pam-ssh-2fa-server.log"
        self.tls_cert = ""
        self.tls_key = ""

        self._load_config(config_file)

    def _load_config(self, config_file: str):
        """Load configuration from INI file."""
        if not os.path.exists(config_file):
            return

        parser = configparser.ConfigParser()
        try:
            parser.read(config_file)
        except configparser.Error:
            return

        # Server settings
        if parser.has_option("server", "port"):
            try:
                self.port = int(parser.get("server", "port"))
            except ValueError:
                pass

        if parser.has_option("server", "bind_address"):
            self.bind_address = parser.get("server", "bind_address")

        if parser.has_option("server", "tls_cert"):
            self.tls_cert = parser.get("server", "tls_cert")

        if parser.has_option("server", "tls_key"):
            self.tls_key = parser.get("server", "tls_key")

        # General settings
        if parser.has_option("general", "debug"):
            self.debug = parser.get("general", "debug").lower() in ("true", "yes", "1")

        if parser.has_option("server", "log_file"):
            self.log_file = parser.get("server", "log_file")

        # Approvals directory (derived from code storage dir)
        if parser.has_option("codes", "storage_dir"):
            storage_dir = parser.get("codes", "storage_dir")
            self.approvals_dir = os.path.join(storage_dir, "approvals")


# =============================================================================
# APPROVAL MANAGER
# =============================================================================


class ApprovalManager:
    """
    Manages approval request files.

    Approval files are JSON with structure:
    {
        "token": "abc123...",
        "user": "username",
        "rhost": "192.168.1.1",
        "host": "servername",
        "created": 1234567890.123,
        "expires": 1234567890.123,
        "approved": false,
        "approved_at": null
    }

    Attributes:
        approvals_dir (str): Directory containing approval files
    """

    def __init__(self, approvals_dir: str):
        """
        Initialize the approval manager.

        Args:
            approvals_dir: Directory for approval request files
        """
        self.approvals_dir = approvals_dir
        self._ensure_dir()

    def _ensure_dir(self):
        """Create approvals directory if it doesn't exist."""
        if not os.path.exists(self.approvals_dir):
            try:
                os.makedirs(self.approvals_dir, mode=0o700)
            except OSError:
                pass

    def get_approval_file(self, token: str) -> str:
        """
        Get the path to an approval file by token.

        Args:
            token: The approval token

        Returns:
            Full path to the approval file
        """
        if not re.fullmatch(r"[A-Za-z0-9_-]{32,128}", token):
            raise ValueError("invalid approval token")
        return os.path.join(self.approvals_dir, f"{token}.json")

    def get_approval(self, token: str) -> Optional[dict]:
        """
        Load an approval request by token.

        Args:
            token: The approval token

        Returns:
            Approval data dict, or None if not found/invalid
        """
        try:
            filepath = self.get_approval_file(token)
        except ValueError:
            return None

        if not os.path.exists(filepath):
            return None

        try:
            with open(filepath, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return None

    def mark_approved(
        self, token: str, confirmation_token: str
    ) -> Tuple[bool, Optional[dict]]:
        """
        Mark an approval request as approved.

        Args:
            token: The approval token

        Returns:
            Tuple of (success, approval_data)
            - success: True if approval was successful
            - approval_data: The approval data dict (for display)
        """
        approval = self.get_approval(token)

        if approval is None:
            logging.warning(f"Approval not found: {token[:8]}...")
            return False, None

        expected_confirmation = approval.get("confirmation_token", "")
        if not expected_confirmation or not secrets.compare_digest(
            confirmation_token, expected_confirmation
        ):
            logging.warning(f"Invalid confirmation token: {token[:8]}...")
            return False, approval

        # Check if already approved
        if approval.get("approved"):
            logging.info(f"Approval already granted: {token[:8]}...")
            return False, approval

        # Check if expired
        if time.time() > approval.get("expires", 0):
            logging.warning(f"Approval expired: {token[:8]}...")
            return False, None

        # Mark as approved
        approval["approved"] = True
        approval["approved_at"] = time.time()

        # Write back
        filepath = self.get_approval_file(token)
        try:
            # Write a complete file and atomically replace the old state so a
            # PAM reader never observes partially written JSON.
            fd, temporary_path = tempfile.mkstemp(
                dir=self.approvals_dir, prefix=".approval-", text=True
            )
            try:
                os.fchmod(fd, 0o600)
                with os.fdopen(fd, "w") as f:
                    json.dump(approval, f)
                    f.flush()
                    os.fsync(f.fileno())
                os.replace(temporary_path, filepath)
            except Exception:
                try:
                    os.unlink(temporary_path)
                except OSError:
                    pass
                raise

            logging.info(
                f"Approval granted: user={approval.get('user')}, "
                f"rhost={approval.get('rhost')}, token={token[:8]}..."
            )
            return True, approval

        except IOError as e:
            logging.error(f"Failed to write approval: {e}")
            return False, None

    def cleanup_expired(self):
        """Remove expired approval files."""
        if not os.path.exists(self.approvals_dir):
            return

        now = time.time()
        cleaned = 0

        for filename in os.listdir(self.approvals_dir):
            if not filename.endswith(".json"):
                continue

            filepath = os.path.join(self.approvals_dir, filename)
            try:
                with open(filepath, "r") as f:
                    data = json.load(f)

                if now > data.get("expires", 0):
                    os.unlink(filepath)
                    cleaned += 1
            except (json.JSONDecodeError, IOError, OSError):
                # Remove corrupt files
                try:
                    os.unlink(filepath)
                    cleaned += 1
                except OSError:
                    pass

        if cleaned > 0:
            logging.debug(f"Cleaned up {cleaned} expired approval(s)")


# =============================================================================
# HTTP REQUEST HANDLER
# =============================================================================


class ApprovalRequestHandler(BaseHTTPRequestHandler):
    """
    HTTP request handler for approval endpoints.

    Endpoints:
        GET /approve/<token>  - Display an authentication request
        POST /approve/<token> - Explicitly approve the request
        GET /health           - Health check

    The handler accesses the ApprovalManager via server.approval_manager.
    """

    # Suppress default logging (we do our own)
    def log_message(self, format, *args):
        logging.debug(f"HTTP: {args[0]}")

    def _send_html(self, status: int, html: str):
        """Send an HTML response."""
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Security-Policy", "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.end_headers()
        self.wfile.write(html.encode("utf-8"))

    def _send_json(self, status: int, data: str):
        """Send a JSON response."""
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(data.encode("utf-8"))

    def do_GET(self):
        """Handle GET requests."""
        parsed = urlparse(self.path)
        path = parsed.path

        # Health check endpoint
        if path == "/health":
            self._handle_health()
            return

        # Approval endpoint: /approve/<token>
        if path.startswith("/approve/"):
            token = path[9:]  # Remove "/approve/" prefix
            self._handle_confirmation_page(token)
            return

        # Root path - simple info
        if path == "/":
            self._handle_root()
            return

        # 404 for anything else
        self._send_html(
            404,
            HTML_ERROR.format(
                title="Not Found", message="The requested page was not found."
            ),
        )

    def do_POST(self):
        """Approve a request only after an explicit form submission."""
        path = urlparse(self.path).path
        if not path.startswith("/approve/"):
            self._send_error(404, "Not Found", "The requested page was not found.")
            return

        try:
            content_length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            content_length = 0
        if content_length <= 0 or content_length > 4096:
            self._send_error(400, "Invalid Request", "Invalid form submission.")
            return

        try:
            form = parse_qs(
                self.rfile.read(content_length).decode("utf-8"),
                strict_parsing=True,
                max_num_fields=4,
            )
        except (UnicodeDecodeError, ValueError):
            self._send_error(400, "Invalid Request", "Invalid form submission.")
            return

        values = form.get("confirmation_token", [])
        if len(values) != 1:
            self._send_error(400, "Invalid Request", "Missing confirmation token.")
            return
        self._handle_approve(path[9:], values[0])

    def _send_error(self, status: int, title: str, message: str):
        self._send_html(
            status,
            HTML_ERROR.format(title=html.escape(title), message=html.escape(message)),
        )

    def _handle_root(self):
        """Handle requests to root path."""
        html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PAM SSH 2FA Approval Server</title>
</head>
<body>
    <h1>PAM SSH 2FA Approval Server</h1>
    <p>This server handles SSH authentication approvals.</p>
    <p>Approval links are sent via push notification.</p>
</body>
</html>"""
        self._send_html(200, html)

    def _handle_health(self):
        """Handle health check requests."""
        timestamp = datetime.now(timezone.utc).isoformat()
        self._send_json(200, json.dumps({"status": "ok", "timestamp": timestamp}))

    def _handle_confirmation_page(self, token: str):
        """Display request details without changing approval state."""
        approval = self.server.approval_manager.get_approval(token)
        if approval is None:
            self._send_error(404, "Invalid Link", "This approval link is invalid.")
            return
        if time.time() > approval.get("expires", 0):
            self._send_error(410, "Link Expired", "This approval link has expired.")
            return
        if approval.get("approved"):
            self._send_error(409, "Already Approved", "This request was already approved.")
            return

        self._send_html(
            200,
            HTML_CONFIRM.format(
                user=html.escape(str(approval.get("user", "unknown"))),
                host=html.escape(str(approval.get("host", "unknown"))),
                rhost=html.escape(str(approval.get("rhost", "unknown"))),
                token=html.escape(token, quote=True),
                confirmation_token=html.escape(
                    str(approval.get("confirmation_token", "")), quote=True
                ),
            ),
        )

    def _handle_approve(self, token: str, confirmation_token: str):
        """
        Handle approval requests.

        Args:
            token: The approval token from the URL
        """
        if not token:
            self._send_html(
                400,
                HTML_ERROR.format(
                    title="Invalid Request", message="No approval token provided."
                ),
            )
            return

        # Get the approval manager from the server
        manager = self.server.approval_manager

        # Attempt to mark as approved
        success, approval = manager.mark_approved(token, confirmation_token)

        if success and approval:
            # Format the response with approval details
            approved_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            self._send_html(
                200,
                HTML_SUCCESS.format(
                    user=html.escape(str(approval.get("user", "unknown"))),
                    host=html.escape(str(approval.get("host", "unknown"))),
                    rhost=html.escape(str(approval.get("rhost", "unknown"))),
                    time=approved_time,
                ),
            )
        else:
            # Check why it failed
            approval_data = manager.get_approval(token)
            if approval_data is None:
                self._send_html(
                    404,
                    HTML_ERROR.format(
                        title="Invalid Link",
                        message="This approval link is invalid or has already been used.",
                    ),
                )
            elif time.time() > approval_data.get("expires", 0):
                self._send_html(
                    410,
                    HTML_ERROR.format(
                        title="Link Expired",
                        message="This approval link has expired. Please try connecting again.",
                    ),
                )
            elif approval_data.get("approved"):
                self._send_error(
                    409, "Already Approved", "This request was already approved."
                )
            elif approval is not None:
                self._send_error(
                    403, "Confirmation Failed", "The confirmation was not accepted."
                )
            else:
                self._send_html(
                    500,
                    HTML_ERROR.format(
                        title="Server Error",
                        message="An error occurred processing your request. Please try again.",
                    ),
                )


# =============================================================================
# APPROVAL SERVER
# =============================================================================


class ApprovalServer(HTTPServer):
    """
    HTTP(S) server for handling approval requests.

    Extends HTTPServer to include the ApprovalManager instance and,
    when a certificate and key are supplied, to serve HTTPS directly
    instead of plain HTTP. Approval links are bearer credentials --
    anyone who observes one in transit can approve the associated SSH
    login -- so a production deployment reachable outside a trusted
    private network must use one of:

    - Native TLS here (tls_cert/tls_key both set)
    - A TLS-terminating reverse proxy in front of plain HTTP
    - A private-network-only URL (Tailscale, VPN, loopback) -- see
      ApprovalManager._check_server_url_security() in pam_ssh_2fa.py,
      which enforces this on the link-generation side
    """

    def __init__(
        self,
        bind_address: str,
        port: int,
        approval_manager: ApprovalManager,
        tls_cert: Optional[str] = None,
        tls_key: Optional[str] = None,
    ):
        """
        Initialize the approval server.

        Args:
            bind_address: Address to bind to (e.g., "0.0.0.0")
            port: Port to listen on
            approval_manager: ApprovalManager instance for handling approvals
            tls_cert: Path to a PEM certificate (chain) file. Must be
                given together with tls_key, or not at all.
            tls_key: Path to the PEM private key matching tls_cert.

        Raises:
            ValueError: If exactly one of tls_cert/tls_key is given
            ssl.SSLError: If the certificate/key can't be loaded
            OSError: If a given path doesn't exist or isn't readable
        """
        if bool(tls_cert) != bool(tls_key):
            raise ValueError(
                "tls_cert and tls_key must both be set, or neither "
                "(a half-configured TLS setup is refused rather than "
                "silently falling back to plain HTTP)"
            )

        super().__init__((bind_address, port), ApprovalRequestHandler)
        self.approval_manager = approval_manager
        self.tls_enabled = False

        if tls_cert and tls_key:
            context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
            context.minimum_version = ssl.TLSVersion.TLSv1_2
            context.load_cert_chain(certfile=tls_cert, keyfile=tls_key)
            self.socket = context.wrap_socket(self.socket, server_side=True)
            self.tls_enabled = True


# =============================================================================
# CLEANUP THREAD
# =============================================================================


class CleanupThread(threading.Thread):
    """
    Background thread that periodically cleans up expired approvals.

    Runs every 60 seconds to remove expired approval files.
    """

    def __init__(self, approval_manager: ApprovalManager):
        super().__init__(daemon=True)
        self.approval_manager = approval_manager
        self.running = True

    def run(self):
        """Run the cleanup loop."""
        while self.running:
            try:
                self.approval_manager.cleanup_expired()
            except Exception as e:
                logging.error(f"Cleanup error: {e}")

            # Sleep for 60 seconds, checking for stop every second
            for _ in range(60):
                if not self.running:
                    break
                time.sleep(1)

    def stop(self):
        """Stop the cleanup thread."""
        self.running = False


# =============================================================================
# MAIN
# =============================================================================


def main():
    """Main entry point for the approval server."""
    parser = argparse.ArgumentParser(
        description="PAM SSH 2FA Approval Server",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This server handles link-based SSH authentication approvals.
Run as a systemd service for production use.

Examples:
  %(prog)s                      Run with default settings
  %(prog)s --port 9110          Run on specific port
  %(prog)s --debug              Enable debug logging
  %(prog)s --tls-cert fullchain.pem --tls-key privkey.pem
                                 Serve HTTPS directly instead of relying
                                 on a reverse proxy
        """,
    )

    parser.add_argument(
        "--config",
        "-c",
        default=DEFAULT_CONFIG_FILE,
        help=f"Path to config file (default: {DEFAULT_CONFIG_FILE})",
    )

    parser.add_argument(
        "--port", "-p", type=int, help="Port to listen on (overrides config file)"
    )

    parser.add_argument("--bind", "-b", help="Address to bind to (default: 0.0.0.0)")

    parser.add_argument(
        "--debug", "-d", action="store_true", help="Enable debug logging"
    )

    parser.add_argument(
        "--tls-cert", help="Path to a PEM certificate file (overrides config file)"
    )

    parser.add_argument(
        "--tls-key", help="Path to the PEM private key (overrides config file)"
    )

    args = parser.parse_args()

    # Load configuration
    config = ServerConfig(args.config)

    # Command line overrides
    if args.port:
        config.port = args.port
    if args.bind:
        config.bind_address = args.bind
    if args.debug:
        config.debug = True
    if args.tls_cert:
        config.tls_cert = args.tls_cert
    if args.tls_key:
        config.tls_key = args.tls_key

    # Setup logging
    setup_logging(debug=config.debug, log_file=config.log_file)

    # Create approval manager
    approval_manager = ApprovalManager(config.approvals_dir)

    # Start cleanup thread
    cleanup_thread = CleanupThread(approval_manager)
    cleanup_thread.start()

    # Create and start server
    try:
        server = ApprovalServer(
            config.bind_address,
            config.port,
            approval_manager,
            tls_cert=config.tls_cert or None,
            tls_key=config.tls_key or None,
        )
    except (ValueError, OSError, ssl.SSLError) as e:
        logging.error(f"Failed to start server: {e}")
        cleanup_thread.stop()
        sys.exit(1)

    logging.info(f"PAM SSH 2FA Approval Server starting")
    scheme = "https" if server.tls_enabled else "http"
    logging.info(f"Listening on {scheme}://{config.bind_address}:{config.port}")
    if not server.tls_enabled:
        logging.warning(
            "Serving plain HTTP -- approval links are bearer credentials. "
            "Use tls_cert/tls_key, a TLS-terminating reverse proxy, or "
            "confine this deployment to a private network."
        )
    logging.info(f"Approvals directory: {config.approvals_dir}")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logging.info("Shutting down...")
    finally:
        cleanup_thread.stop()
        server.shutdown()

    logging.info("Server stopped")


if __name__ == "__main__":
    main()
